export const GET_MOVIES_LIST = {
    REQUEST: 'GET_MOVIES_LIST_REQUEST',
    SUCCESS: 'GET_MOVIES_LIST_SUCCESS',
    FAILURE: 'GET_MOVIES_LIST_FAILURE',
    REFRESH: 'GET_MOVIES_LIST_REFRESH',
  };
  
  export const GET_MOVIES_CAROUSEL_LIST = {
    REQUEST: 'GET_MOVIES_CAROUSEL_LIST_REQUEST',
    SUCCESS: 'GET_MOVIES_CAROUSEL_LIST_SUCCESS',
    FAILURE: 'GET_MOVIES_CAROUSEL_LIST_FAILURE',
    REFRESH: 'GET_MOVIES_CAROUSEL_LIST_REFRESH',
  };

  export const GET_TV_LIST = {
    REQUEST: 'GET_TV_LIST_REQUEST',
    SUCCESS: 'GET_TV_LIST_SUCCESS',
    FAILURE: 'GET_TV_LIST_FAILURE',
    REFRESH: 'GET_TV_LIST_REFRESH',
  };

  export const GET_VIDEOS = {
    REQUEST: 'GET_VIDEOS_REQUEST',
    SUCCESS: 'GET_VIDEOS_SUCCESS',
    FAILURE: 'GET_VIDEOS_FAILURE',
    REFRESH: 'GET_VIDEOS_REFRESH',
  };

  export const GET_DETAIL_MOVIE = {
    REQUEST: 'GET_DETAIL_MOVIE_REQUEST',
    SUCCESS: 'GET_DETAIL_MOVIE_SUCCESS',
    FAILURE: 'GET_DETAIL_MOVIE_FAILURE',
    REFRESH: 'GET_DETAIL_MOVIE_REFRESH',
  };

  export const GET_CREDITS_LIST = {
    REQUEST: 'GET_CREDITS_LIST_REQUEST',
    SUCCESS: 'GET_CREDITS_LIST_SUCCESS',
    FAILURE: 'GET_CREDITS_LIST_FAILURE',
    REFRESH: 'GET_CREDITS_LIST_REFRESH',
  };
  export const SEARCH_DETAIL_MOVIE = {
    REQUEST: 'SEARCH_DETAIL_MOVIE_REQUEST',
    SUCCESS: 'SEARCH_DETAIL_MOVIE_SUCCESS',
    FAILURE: 'SEARCH_DETAIL_MOVIE_FAILURE',
    REFRESH: 'SEARCH_DETAIL_MOVIE_REFRESH',
  };
  export const GET_SIMILAR_LIST = {
    REQUEST: 'GET_SIMILAR_LIST_REQUEST',
    SUCCESS: 'GET_SIMILAR_LIST_SUCCESS',
    FAILURE: 'GET_SIMILAR_LIST_FAILURE',
    REFRESH: 'GET_SIMILAR_LIST_REFRESH',
  };